# Generated by Django 3.2a1 on 2024-04-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customblacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomBlacklistedToken',
        ),
    ]
