# Generated by Django 3.2a1 on 2024-04-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
